install.packages("rmarkdown")
install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
book <- read.csv("C:\\Users\\suman\\Desktop\\Assignment\\DS Assignment\\book.csv")
View(book)
rules <- apriori(as.matrix(book),parameter=list(support=0.02, confidence = 0.5,minlen=5))
rules
inspect(head(sort(rules, by = "lift")))  
head(quality(rules))
plot(rules,method = "scatterplot")
plot(rules,method = "grouped")
plot(rules,method = "graph")
